name: CI

on:
  push:
    branches:
      - main

jobs:
  grype-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Grype
        run: curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Update Grype database
        run: grype db update

      - name: Run Grype scan
        run: grype .